### ISSUE TITLE
Instance raises Conflicting configuration actions

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.newsticker#29]
* Plone 4.3.11
* collective.lazysizes 2.0.5rc1
* collective.newsticker 2.1b1

Instance don't start and raise  the following error:

```
2017-03-21 17:48:29 INFO ZEO.ClientStorage zeostorage Disconnected from storage: "('localhost', 8100)"
Traceback (most recent call last):
  File "/opt/plone/buildout/parts/instance1/bin/interpreter", line 384, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/opt/plone/buildout/eggs/Zope2-2.13.24-py2.7.egg/Zope2/Startup/run.py", line 76, in <module>
    run()
  File "/opt/plone/buildout/eggs/Zope2-2.13.24-py2.7.egg/Zope2/Startup/run.py", line 22, in run
    starter.prepare()
  File "/opt/plone/buildout/eggs/Zope2-2.13.24-py2.7.egg/Zope2/Startup/__init__.py", line 92, in prepare
    self.startZope()
  File "/opt/plone/buildout/eggs/Zope2-2.13.24-py2.7.egg/Zope2/Startup/__init__.py", line 268, in startZope
    Zope2.startup()
  File "/opt/plone/buildout/eggs/Zope2-2.13.24-py2.7.egg/Zope2/__init__.py", line 47, in startup
    _startup()
  File "/opt/plone/buildout/eggs/Zope2-2.13.24-py2.7.egg/Zope2/App/startup.py", line 118, in startup
    load_zcml()
  File "/opt/plone/buildout/eggs/Zope2-2.13.24-py2.7.egg/Zope2/App/startup.py", line 52, in load_zcml
    load_site()
  File "/opt/plone/buildout/eggs/Zope2-2.13.24-py2.7.egg/Zope2/App/zcml.py", line 46, in load_site
    _context = xmlconfig.file(site_zcml)
  File "/opt/plone/buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 651, in file
    context.execute_actions()
  File "/opt/plone/buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 620, in execute_actions
    for action in resolveConflicts(self.actions):
  File "/opt/plone/buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 1527, in resolveConflicts
    raise ConfigurationConflictError(conflicts)
zope.configuration.config.ConfigurationConflictError: Conflicting configuration actions
  For: ('upgradeDepends', '1', '2', None, "[u'plone.app.registry']", 0)
    File "/opt/plone/buildout/eggs/collective.lazysizes-2.0.5rc1-py2.7.egg/collective/lazysizes/upgrades/v2/configure.zcml", line 18.4-23.10
          <genericsetup:upgradeDepends
              title="Add new field to configlet"
              description="Reload registration of configlet registry to add new field."
              import_steps="plone.app.registry"
              run_deps="false"
              />
    File "/opt/plone/buildout/eggs/collective.newsticker-2.1b1-py2.7.egg/collective/newsticker/upgrades/v2/configure.zcml", line 12.4-17.10
          <genericsetup:upgradeDepends
              title="Add 'enabled' field to configlet"
              description="Reload registration of configlet registry to add new field."
              import_steps="plone.app.registry"
              run_deps="false"
              />
```

**Comment by hvelarde** [comment]
workaround is to skip the upgrade step registration for one of the packages.

**Comment by rodfersou** [comment]
https://github.com/zopefoundation/Products.GenericSetup/issues/7#issuecomment-237272961
